### PR TITLE
Settings for Dev contributions

### PR DESCRIPTION
**Pull request by mukkoo**
I've added settings and readme for dev contributions (run static files locally with express.js).

### CODE REVIEW

**Comment by matjack1** [comment]
I'm not against this, but if you have Python installed you can do:
`python -m SimpleHTTPServer 3000`
from the project folder and have the same result.

**Comment by grigio** [comment]
I use an alias to what @matjack1 wrote. It is present by default in any OS without installing anything :)

**Comment by antonellopasella** [comment]
Also php -S 127.0.0.1


## 

Antonello Pasella http://www.pasella.it

**Comment by grigio** [comment]
The point is that it is a static page to be simple and neutral, anybody shouldn't be forced to use a particular technology to have a webserver.

My proposal:

Se vuoi provare in locale il sito hai bisogno di un web server. Vai dentro la cartella e digita uno dei seguenti comandi  https://gist.github.com/willurd/5720255

**Comment by mukkoo** [comment]
Good proposal! +1

**Pull request closed without merging**
